apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-config
  namespace: livekit
data:
  livekit.yaml: |
    port: 7880
    log_level: info
    rtc:
      port_range_start: 50000
      port_range_end: 50100
      tcp_port: 7881
      use_external_ip: false
    keys:
      devkey: kypjmViV2UC2RK0gAcvAv7Hhwtg/88HpedMMKgfWffY=
    turn:
      enabled: true
      domain: livekit-server
      tls_port: 0
      udp_port: 3478
